<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-AU847K4" failures="1" tests="5" name="Automation Test" time="0.368" errors="0" timestamp="2025-02-20T18:35:17 IST">
  <testcase classname="tests.LoginTest2" name="loginwithValidCredientials" time="0.063"/>
  <testcase classname="tests.LoginTest2" name="loginwithInvalidUser" time="0.028">
    <failure type="java.lang.AssertionError" message="loginwithInvalidUser got failed">
      <![CDATA[java.lang.AssertionError: loginwithInvalidUser got failed
at tests.LoginTest2.loginwithInvalidUser(LoginTest2.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- loginwithInvalidUser -->
  <testcase classname="tests.LoginTest2" name="loginwithInvalidpassword" time="0.065"/>
  <testcase classname="tests.LoginTest2" name="loginwithInValidCredientials" time="0.009"/>
  <testcase classname="tests.LoginTest2" name="loginwithEmptyFields" time="0.009"/>
</testsuite> <!-- Automation Test -->
